hostsdir=/etc/dnsmasq.d/ # inotify watches the dir

no-resolv

server=1.1.1.1
server=8.8.8.8

listen-address=127.0.0.1

bind-interfaces
interface=ceth1

# Local domain configuration
local-service
local=/service.local/
expand-hosts

# This creates an A record for dnsmasq.  Put all others in /etc/dnsmasq.d/.
interface-name=dnsmasq.service.local,ceth1

# Create an SRV record for dnsmasq.  I don't think that others can be
# dynamically added.
# dig @172.16.2.2 +short SRV _dns._udp.dnsmasq.service.local
srv-host=_dns._udp.service.local,dnsmasq.service.local,53,10,50

